"""initial schema

Revision ID: 2ac7f5019a6d
Revises: 
Create Date: 2026-04-23 18:26:05.587855
"""

from alembic import op
import sqlalchemy as sa


revision = '2ac7f5019a6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('segment', sa.String(length=64), nullable=True),
    sa.Column('market_cap_tier', sa.String(length=32), nullable=True),
    sa.Column('ir_url', sa.String(length=256), nullable=True),
    sa.Column('careers_url', sa.String(length=256), nullable=True),
    sa.Column('x_handle', sa.String(length=64), nullable=True),
    sa.Column('ceo_name', sa.String(length=128), nullable=True),
    sa.Column('cik', sa.String(length=16), nullable=True),
    sa.Column('pr_page_url', sa.String(length=256), nullable=True),
    sa.Column('is_benchmark', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_ticker'), ['ticker'], unique=True)

    op.create_table('correlations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('target_name', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('ci_low', sa.Float(), nullable=True),
    sa.Column('ci_high', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('p_adjusted', sa.Float(), nullable=True),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_messages',
    sa.Column('message_id', sa.String(length=256), nullable=False),
    sa.Column('from_addr', sa.String(length=256), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('ticker_mentions', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('macro_observations',
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('series_id', 'obs_date')
    )
    op.create_table('macro_series',
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('latest_value', sa.Float(), nullable=True),
    sa.Column('latest_date', sa.Date(), nullable=True),
    sa.Column('change_90d_pct', sa.Float(), nullable=True),
    sa.Column('change_label', sa.String(length=16), nullable=True),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('bar_width_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('source_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('weather_observations',
    sa.Column('station_id', sa.String(length=32), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('tavg_f', sa.Float(), nullable=True),
    sa.Column('tmax_f', sa.Float(), nullable=True),
    sa.Column('tmin_f', sa.Float(), nullable=True),
    sa.Column('prcp_in', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('station_id', 'obs_date')
    )
    op.create_table('company_signals',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('change_1d_pct', sa.Float(), nullable=True),
    sa.Column('change_5d_pct', sa.Float(), nullable=True),
    sa.Column('change_30d_pct', sa.Float(), nullable=True),
    sa.Column('rs_vs_xly', sa.Float(), nullable=True),
    sa.Column('next_er_date', sa.Date(), nullable=True),
    sa.Column('next_er_time', sa.String(length=4), nullable=True),
    sa.Column('news_7d_count', sa.Integer(), nullable=True),
    sa.Column('news_volume_pct_baseline', sa.Float(), nullable=True),
    sa.Column('sentiment_7d', sa.Float(), nullable=True),
    sa.Column('social_vol_z', sa.Float(), nullable=True),
    sa.Column('jobs_change_30d_pct', sa.Float(), nullable=True),
    sa.Column('hypothesis_label', sa.String(length=16), nullable=True),
    sa.Column('hypothesis_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('earnings',
    sa.Column('earnings_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=16), nullable=True),
    sa.Column('time_of_day', sa.String(length=4), nullable=True),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('eps_actual', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('eps_surprise_pct', sa.Float(), nullable=True),
    sa.Column('hypothesis_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('earnings_id'),
    sa.UniqueConstraint('company_id', 'report_date', name='uq_earnings_co_date')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ticker_label', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=4), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('source_ref', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('filings',
    sa.Column('filing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_type', sa.String(length=16), nullable=False),
    sa.Column('accession_number', sa.String(length=32), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('primary_doc_url', sa.String(length=512), nullable=True),
    sa.Column('item_numbers', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('filing_id')
    )
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filings_accession_number'), ['accession_number'], unique=True)

    op.create_table('jobs_snapshots',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('corporate_count', sa.Integer(), nullable=True),
    sa.Column('by_department', sa.JSON(), nullable=False),
    sa.Column('by_location', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('company_id', 'snapshot_date', name='uq_jobs_co_date')
    )
    op.create_table('news',
    sa.Column('news_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_url_hash'), ['url_hash'], unique=True)

    op.create_table('prices_daily',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('company_id', 'trade_date')
    )
    op.create_table('reddit_posts',
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('subreddit', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('ticker_mentions', sa.JSON(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('social_posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('account', sa.String(length=128), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('engagement', sa.JSON(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_company_official', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_posts_external_id'), ['external_id'], unique=False)

    op.create_table('features_earnings',
    sa.Column('feature_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('earnings_id', sa.Integer(), nullable=False),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('return_30d', sa.Float(), nullable=True),
    sa.Column('volatility_30d', sa.Float(), nullable=True),
    sa.Column('volume_trend_30d', sa.Float(), nullable=True),
    sa.Column('rs_30d', sa.Float(), nullable=True),
    sa.Column('news_sentiment_mean_30d', sa.Float(), nullable=True),
    sa.Column('news_sentiment_trend_30d', sa.Float(), nullable=True),
    sa.Column('news_volume_30d', sa.Integer(), nullable=True),
    sa.Column('news_volume_z', sa.Float(), nullable=True),
    sa.Column('social_sentiment_mean_30d', sa.Float(), nullable=True),
    sa.Column('social_volume_30d', sa.Integer(), nullable=True),
    sa.Column('jobs_count_change_90d', sa.Float(), nullable=True),
    sa.Column('jobs_corporate_change_90d', sa.Float(), nullable=True),
    sa.Column('filings_8k_count_30d', sa.Integer(), nullable=True),
    sa.Column('filings_exec_change', sa.Boolean(), nullable=True),
    sa.Column('beef_change_90d', sa.Float(), nullable=True),
    sa.Column('chicken_change_90d', sa.Float(), nullable=True),
    sa.Column('wheat_change_90d', sa.Float(), nullable=True),
    sa.Column('gas_change_90d', sa.Float(), nullable=True),
    sa.Column('cons_sentiment_level', sa.Float(), nullable=True),
    sa.Column('cons_sentiment_change_90d', sa.Float(), nullable=True),
    sa.Column('unemployment_change_90d', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['earnings_id'], ['earnings.earnings_id'], ),
    sa.PrimaryKeyConstraint('feature_id'),
    sa.UniqueConstraint('earnings_id', 'feature_version', name='uq_features_earn_ver')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features_earnings')
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_posts_external_id'))

    op.drop_table('social_posts')
    op.drop_table('reddit_posts')
    op.drop_table('prices_daily')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_url_hash'))

    op.drop_table('news')
    op.drop_table('jobs_snapshots')
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filings_accession_number'))

    op.drop_table('filings')
    op.drop_table('events')
    op.drop_table('earnings')
    op.drop_table('company_signals')
    op.drop_table('weather_observations')
    op.drop_table('source_runs')
    op.drop_table('macro_series')
    op.drop_table('macro_observations')
    op.drop_table('email_messages')
    op.drop_table('correlations')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_ticker'))

    op.drop_table('companies')
    op.drop_table('briefings')
    # ### end Alembic commands ###
