/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Universe */
        get: operations["list_universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Briefing */
        get: operations["get_briefing_api_briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/earnings/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming */
        get: operations["upcoming_api_earnings_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Earnings
         * @description Calendar view: one row per earnings event with outcome if available.
         */
        get: operations["list_earnings_api_earnings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/earnings/{earnings_id}/postmortem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Postmortem */
        get: operations["get_postmortem_api_earnings__earnings_id__postmortem_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Macro */
        get: operations["list_macro_api_macro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Macro Series */
        get: operations["get_macro_series_api_macro__series_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_companies__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{ticker}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Prices */
        get: operations["get_company_prices_api_companies__ticker__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List News */
        get: operations["list_news_api_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Filings */
        get: operations["list_filings_api_filings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Social */
        get: operations["list_social_api_social_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social/reddit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reddit */
        get: operations["list_reddit_api_social_reddit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/correlations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Correlations */
        get: operations["list_correlations_api_analysis_correlations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/features/{earnings_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feature Vector */
        get: operations["get_feature_vector_api_analysis_features__earnings_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/axes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Axes */
        get: operations["get_axes_api_analysis_axes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/scatter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scatter */
        get: operations["get_scatter_api_analysis_scatter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Heatmap */
        get: operations["get_heatmap_api_analysis_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/attribution/{earnings_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attribution */
        get: operations["get_attribution_api_analysis_attribution__earnings_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/regression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Regressions */
        get: operations["get_regressions_api_analysis_regression_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hypotheses */
        get: operations["list_hypotheses_api_hypotheses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/source-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_ops_source_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisAxesResponse */
        AnalysisAxesResponse: {
            /** Features */
            features: string[];
            /** Targets */
            targets: string[];
        };
        /** BriefingOut */
        BriefingOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Token Count */
            token_count: number;
            /** Sections */
            sections: components["schemas"]["BriefingSection"][];
        };
        /** BriefingResponse */
        BriefingResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            stats: components["schemas"]["StatSummary"];
            briefing: components["schemas"]["BriefingOut"];
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Universe */
            universe: components["schemas"]["UniverseRow"][];
            /** Macro */
            macro: components["schemas"]["MacroRow"][];
            /** Upcoming Earnings */
            upcoming_earnings: components["schemas"]["UpcomingEarnings"][];
        };
        /** BriefingSection */
        BriefingSection: {
            /** Heading */
            heading: string;
            /** Body */
            body: string;
        };
        /** ChartMarker */
        ChartMarker: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Severity */
            severity: string;
            /** Source */
            source: string | null;
            /** Description */
            description: string;
            /** Event Type */
            event_type: string;
        };
        /** CoefficientOut */
        CoefficientOut: {
            /** Feature */
            feature: string;
            /** Value */
            value: number;
            /** Abs Value */
            abs_value: number;
        };
        /** CompanyDetail */
        CompanyDetail: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Segment */
            segment: string | null;
            /** Market Cap Tier */
            market_cap_tier: string | null;
            /** Ir Url */
            ir_url: string | null;
            /** Careers Url */
            careers_url: string | null;
            /** Ceo Name */
            ceo_name: string | null;
            /** Cik */
            cik: string | null;
            signals: components["schemas"]["UniverseRow"];
        };
        /** CompanyPriceHistory */
        CompanyPriceHistory: {
            /** Ticker */
            ticker: string;
            /** Bars */
            bars: components["schemas"]["PriceBar"][];
            /** Markers */
            markers: components["schemas"]["ChartMarker"][];
        };
        /** CorrelationOut */
        CorrelationOut: {
            /** Feature Name */
            feature_name: string;
            /** Target Name */
            target_name: string;
            /** Method */
            method: string;
            /** N */
            n: number;
            /** Coefficient */
            coefficient: number | null;
            /** Ci Low */
            ci_low: number | null;
            /** Ci High */
            ci_high: number | null;
            /** P Value */
            p_value: number | null;
            /** P Adjusted */
            p_adjusted: number | null;
        };
        /** EarningsPostmortemOut */
        EarningsPostmortemOut: {
            /** Earnings Id */
            earnings_id: number;
            /** Ticker */
            ticker: string;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Fiscal Period */
            fiscal_period: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Model */
            model: string;
            /** Token Count */
            token_count: number;
            /** Headline */
            headline: string;
            /** Narrative */
            narrative: string;
            /** Tags */
            tags: string[];
        };
        /** EarningsRow */
        EarningsRow: {
            /** Earnings Id */
            earnings_id: number;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Fiscal Period */
            fiscal_period: string | null;
            /** Time Of Day */
            time_of_day: string | null;
            /** Eps Estimate */
            eps_estimate: number | null;
            /** Eps Actual */
            eps_actual: number | null;
            /** Revenue Estimate */
            revenue_estimate: number | null;
            /** Revenue Actual */
            revenue_actual: number | null;
            /** Eps Beat */
            eps_beat: boolean | null;
            /** Eps Surprise Pct */
            eps_surprise_pct: number | null;
            /** Post Earnings 1D Return */
            post_earnings_1d_return: number | null;
            /** Post Earnings 5D Return */
            post_earnings_5d_return: number | null;
            /** Reaction */
            reaction: string | null;
            /** Hypothesis Score */
            hypothesis_score: number | null;
            /** Hypothesis Label */
            hypothesis_label: string | null;
        };
        /** EventAttributionResponse */
        EventAttributionResponse: {
            /** Earnings Id */
            earnings_id: number;
            /** Ticker */
            ticker: string;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Target */
            target: string;
            /** Prediction */
            prediction: number;
            /** Intercept */
            intercept: number;
            /** R Squared */
            r_squared: number;
            /** Contributions */
            contributions: components["schemas"]["FeatureContribution"][];
        };
        /** EventOut */
        EventOut: {
            /** Ticker */
            ticker: string;
            /** Event Type */
            event_type: string;
            /**
             * Event At
             * Format: date-time
             */
            event_at: string;
            /** Severity */
            severity: string;
            /** Source */
            source?: string | null;
            /** Description */
            description: string;
            /** Time Label */
            time_label: string;
        };
        /** FeatureContribution */
        FeatureContribution: {
            /** Feature */
            feature: string;
            /** Value */
            value: number;
            /** Coefficient */
            coefficient: number;
            /** Contribution */
            contribution: number;
        };
        /** FeatureVectorOut */
        FeatureVectorOut: {
            /** Earnings Id */
            earnings_id: number;
            /** Ticker */
            ticker: string;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Feature Version */
            feature_version: string;
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** FilingOut */
        FilingOut: {
            /** Filing Id */
            filing_id: number;
            /** Ticker */
            ticker: string;
            /** Filing Type */
            filing_type: string;
            /**
             * Filed At
             * Format: date-time
             */
            filed_at: string;
            /** Primary Doc Url */
            primary_doc_url: string | null;
            /** Item Numbers */
            item_numbers: string[];
            /** Title */
            title: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatmapResponse */
        HeatmapResponse: {
            /** Method */
            method: string;
            /** Features */
            features: string[];
            /** Matrix */
            matrix: (number | null)[][];
            /** Sample Sizes */
            sample_sizes: number[][];
        };
        /** HypothesisTrackerRow */
        HypothesisTrackerRow: {
            /** Ticker */
            ticker: string;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Fiscal Period */
            fiscal_period: string | null;
            /** Hypothesis Score */
            hypothesis_score: number | null;
            /** Hypothesis Label */
            hypothesis_label: string | null;
            /** Actual */
            actual: string | null;
            /** Reaction */
            reaction: string | null;
            /** Eps Surprise Pct */
            eps_surprise_pct: number | null;
            /** Post Earnings 1D Return */
            post_earnings_1d_return: number | null;
            /** Prediction Correct */
            prediction_correct: boolean | null;
            /**
             * Top Drivers
             * @default []
             */
            top_drivers: components["schemas"]["FeatureContribution"][];
        };
        /** HypothesisTrackerSummary */
        HypothesisTrackerSummary: {
            /** Total */
            total: number;
            /** Scored */
            scored: number;
            /** Correct */
            correct: number;
            /** Accuracy Pct */
            accuracy_pct: number | null;
            /** Rows */
            rows: components["schemas"]["HypothesisTrackerRow"][];
        };
        /** JobsSnapshotOut */
        JobsSnapshotOut: {
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /** Ticker */
            ticker: string;
            /** Total Count */
            total_count: number | null;
            /** Corporate Count */
            corporate_count: number | null;
            /** By Department */
            by_department: {
                [key: string]: unknown;
            };
            /** By Location */
            by_location: {
                [key: string]: unknown;
            };
        };
        /** MacroRow */
        MacroRow: {
            /** Series Id */
            series_id: string;
            /** Label */
            label: string;
            /** Latest Value */
            latest_value: number | null;
            /** Change 90D Pct */
            change_90d_pct: number | null;
            /** Change Label */
            change_label: string | null;
            /** Direction */
            direction: string;
            /** Bar Width Pct */
            bar_width_pct: number;
        };
        /** MacroSeriesDetail */
        MacroSeriesDetail: {
            /** Series Id */
            series_id: string;
            /** Label */
            label: string;
            /** Latest Value */
            latest_value: number | null;
            /** Latest Date */
            latest_date: string | null;
            /** Change 90D Pct */
            change_90d_pct: number | null;
            /** Direction */
            direction: string;
            /** Observations */
            observations: {
                [key: string]: unknown;
            }[];
        };
        /** NewsItemOut */
        NewsItemOut: {
            /** News Id */
            news_id: number;
            /** Ticker */
            ticker: string | null;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Published At */
            published_at: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Headline */
            headline: string;
            /** Publisher */
            publisher: string | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Relevance Score */
            relevance_score: number | null;
            /** Topics */
            topics: string[];
        };
        /** PriceBar */
        PriceBar: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Close */
            close: number | null;
            /** Volume */
            volume: number | null;
        };
        /** RedditPostOut */
        RedditPostOut: {
            /** Post Id */
            post_id: string;
            /** Ticker */
            ticker: string | null;
            /** Subreddit */
            subreddit: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Title */
            title: string;
            /** Score */
            score: number;
            /** Num Comments */
            num_comments: number;
            /** Url */
            url: string | null;
            /** Sentiment Score */
            sentiment_score: number | null;
        };
        /** RegressionFitOut */
        RegressionFitOut: {
            /** Method */
            method: string;
            /** Target */
            target: string;
            /** N */
            n: number;
            /** Features Used */
            features_used: string[];
            /** Intercept */
            intercept: number;
            /** R Squared */
            r_squared: number;
            /** R Squared Loo */
            r_squared_loo: number | null;
            /** Rmse */
            rmse: number;
            /** Coefficients */
            coefficients: components["schemas"]["CoefficientOut"][];
            /** Note */
            note: string | null;
        };
        /** RegressionLineOut */
        RegressionLineOut: {
            /** Slope */
            slope: number;
            /** Intercept */
            intercept: number;
            /** R Squared */
            r_squared: number;
            /** N */
            n: number;
            /** X Min */
            x_min: number;
            /** X Max */
            x_max: number;
            /** Pearson R */
            pearson_r: number | null;
            /** Pearson P */
            pearson_p: number | null;
            /** Spearman R */
            spearman_r: number | null;
            /** Spearman P */
            spearman_p: number | null;
            /** Ci Low At Min */
            ci_low_at_min: number | null;
            /** Ci High At Min */
            ci_high_at_min: number | null;
            /** Ci Low At Max */
            ci_low_at_max: number | null;
            /** Ci High At Max */
            ci_high_at_max: number | null;
        };
        /** ScatterPointOut */
        ScatterPointOut: {
            /** Ticker */
            ticker: string;
            /** Earnings Id */
            earnings_id: number;
            /** Report Date */
            report_date: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ScatterResponse */
        ScatterResponse: {
            /** Feature */
            feature: string;
            /** Target */
            target: string;
            /** Points */
            points: components["schemas"]["ScatterPointOut"][];
            line: components["schemas"]["RegressionLineOut"] | null;
        };
        /** SocialPostOut */
        SocialPostOut: {
            /** Post Id */
            post_id: number;
            /** Ticker */
            ticker: string | null;
            /** Platform */
            platform: string;
            /** Account */
            account: string | null;
            /** Posted At */
            posted_at: string | null;
            /** Content */
            content: string;
            /** Engagement */
            engagement: {
                [key: string]: unknown;
            };
            /** Sentiment Score */
            sentiment_score: number | null;
        };
        /** SourceRunOut */
        SourceRunOut: {
            /** Source Name */
            source_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Status */
            status: string;
            /** Rows Fetched */
            rows_fetched: number;
            /** Error Msg */
            error_msg: string | null;
        };
        /** StatSummary */
        StatSummary: {
            /** Universe Change 1D Pct */
            universe_change_1d_pct: number;
            /** Spy Change 1D Pct */
            spy_change_1d_pct: number;
            /** Up Count */
            up_count: number;
            /** Total Count */
            total_count: number;
            /** Events 24H Total */
            events_24h_total: number;
            /** Events 24H Hi */
            events_24h_hi: number;
            /** Events 24H Md */
            events_24h_md: number;
            /** Events 24H Lo */
            events_24h_lo: number;
            /** Earnings Next 14D */
            earnings_next_14d: number;
            /** Next Earnings Label */
            next_earnings_label: string;
            /** Signal Strength */
            signal_strength: number;
            /** Features Active */
            features_active: number;
            /** Median R */
            median_r: number;
        };
        /** UniverseRow */
        UniverseRow: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Segment */
            segment?: string | null;
            /** Last Price */
            last_price?: number | null;
            /** Change 1D Pct */
            change_1d_pct?: number | null;
            /** Change 5D Pct */
            change_5d_pct?: number | null;
            /** Change 30D Pct */
            change_30d_pct?: number | null;
            /** Rs Vs Xly */
            rs_vs_xly?: number | null;
            /** Next Er Date */
            next_er_date?: string | null;
            /** Next Er Time */
            next_er_time?: string | null;
            /** News 7D Count */
            news_7d_count?: number | null;
            /** News Volume Pct Baseline */
            news_volume_pct_baseline?: number | null;
            /** Sentiment 7D */
            sentiment_7d?: number | null;
            /** Social Vol Z */
            social_vol_z?: number | null;
            /** Jobs Change 30D Pct */
            jobs_change_30d_pct?: number | null;
            /** Hypothesis Label */
            hypothesis_label?: string | null;
            /** Hypothesis Score */
            hypothesis_score?: number | null;
        };
        /** UpcomingEarnings */
        UpcomingEarnings: {
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Time Of Day */
            time_of_day: string | null;
            /** Ticker */
            ticker: string;
            /** Fiscal Period */
            fiscal_period: string | null;
            /** Eps Estimate */
            eps_estimate: number | null;
            /** Revenue Estimate */
            revenue_estimate: number | null;
            /** Hypothesis Label */
            hypothesis_label: string | null;
            /** Hypothesis Score */
            hypothesis_score: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_universe_api_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseRow"][];
                };
            };
        };
    };
    get_briefing_api_briefing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upcoming_api_earnings_upcoming_get: {
        parameters: {
            query?: {
                within_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingEarnings"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_earnings_api_earnings_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                past_only?: boolean;
                upcoming_only?: boolean;
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarningsRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_postmortem_api_earnings__earnings_id__postmortem_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                earnings_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarningsPostmortemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_macro_api_macro_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroRow"][];
                };
            };
        };
    };
    get_macro_series_api_macro__series_id__get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_companies__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_prices_api_companies__ticker__prices_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyPriceHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_news_api_news_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_filings_api_filings_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_social_api_social_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialPostOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reddit_api_social_reddit_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedditPostOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsSnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_correlations_api_analysis_correlations_get: {
        parameters: {
            query?: {
                target?: string | null;
                method?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_vector_api_analysis_features__earnings_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                earnings_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureVectorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_axes_api_analysis_axes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisAxesResponse"];
                };
            };
        };
    };
    get_scatter_api_analysis_scatter_get: {
        parameters: {
            query: {
                feature: string;
                target: string;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScatterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_heatmap_api_analysis_heatmap_get: {
        parameters: {
            query?: {
                method?: string;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attribution_api_analysis_attribution__earnings_id__get: {
        parameters: {
            query?: {
                target?: string;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path: {
                earnings_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAttributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regressions_api_analysis_regression_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegressionFitOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hypotheses_api_hypotheses_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisTrackerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_ops_source_runs_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
